### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by damonjanis** [kfrancis/chargify-dot-net#62]
On calling CreateSubscription this exception is always thrown: System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index'. I've included the exception details below.

I'm using version Chargify.Net 1.2.5 from Nuget on a .Net Framework 4.6.1 project, and Newtonsoft.Json v11.0.2.

Here is the code (this is on a test account so I'm passing "1" for the credit card):

`CustomerAttributes customer = new CustomerAttributes("Damon", "Janis", "test@test.com", "Quest", "7645");`
`CreditCardAttributes creditCard = new CreditCardAttributes("Damon", "Janis", "1", 2022, 4, "123", "150 Rainbow Dr #5022", "Livingston", "TX", "77399", "US");`
`var subscription = ChargifyConnect.CreateSubscription("standard-monthly", customer, creditCard);`

I've tried passing in different information but no matter what I try, the same exception is always thrown. Here are the exception details:

System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  Source=mscorlib
  StackTrace:
   at System.Collections.ArrayList.get_Item(Int32 index)
   at ChargifyNET.Json.XmlToJsonConverter.XmlToJsoNnode(StringBuilder sbJson, XmlElement node, Boolean showNodeName)
   at ChargifyNET.Json.XmlToJsonConverter.OutputNode(String childname, Object alChild, StringBuilder sbJson, Boolean showNodeName)
   at ChargifyNET.Json.XmlToJsonConverter.XmlToJsoNnode(StringBuilder sbJson, XmlElement node, Boolean showNodeName)
   at ChargifyNET.Json.XmlToJsonConverter.XmlToJson(XmlDocument xmlDoc)
   at ChargifyNET.ChargifyConnect.DoRequest(String methodString, HttpRequestMethod requestMethod, String postData)
   at ChargifyNET.ChargifyConnect.CreateSubscription(String productHandle, String newSystemId, String firstName, String lastName, String emailAddress, String phone, String organization, String vatNumber, String shippingAddress, String shippingCity, String shippingState, String shippingZip, String shippingCountry, String fullNumber, Int32 expirationMonth, Int32 expirationYear, String cvv, String billingAddress, String billingCity, String billingState, String billingZip, String billingCountry, String couponCode, Int32 componentId, Int32 allocatedQuantity)
   at ChargifyNET.ChargifyConnect.CreateSubscription(String productHandle, ICustomerAttributes customerAttributes, ICreditCardAttributes creditCardAttributes)
   at questBLL.Chargify.CreateCustomer(String firstName, String lastName, String email, String fullNumber, String cvv, Int32 expirationMonth, Int32 expirationYear, String billingAddress, String billingCity, String billingState, String billingZip) in C:\Users\damonjanis\Dropbox\Data\work\Projects\Quest\Src\BLL\Chargify.cs:line 31
   at TestBLL.Program.Main(String[] args) in C:\Users\damonjanis\Dropbox\Data\work\Projects\Quest\Src\TestBLL\Program.cs:line 19

**Comment by kfrancis** [comment]
I'll take a look.

**Comment by damonjanis** [comment]
Thanks for looking into it! I ran the same code against a different Chargify site and got the same exception. I thought it might be specific to the site but it doesn't appear to be.

**Comment by kfrancis** [comment]
Hmm, none of my create subscription tests appear to fail - checked this one `CreateSubscription(String productHandle, ICustomerAttributes customerAttributes, ICreditCardAttributes creditCardAttributes)`. Still not sure what could be the issue.

**Comment by damonjanis** [comment]
Thank you for double checking. I can't figure out why it throws that exception, but I did find a work around. This call works without throwing the exception:

` ChargifyConnect.CreateSubscription("standard-monthly", "12345", creditCard);`

There is something in the `CreateSubscription(string productHandle, ICustomerAttributes customerAttributes, ICreditCardAttributes creditCardAttributes)` method override that is problematic but the good news is it can be bypassed by using a different override.

Thanks for putting this great library together!

**Comment by kfrancis** [comment]
I would just suggest using the SubscriptionCreateOptions override, but that works too.
